# Generated by Django 3.0.5 on 2020-04-10 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_craft_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='craft',
            old_name='name',
            new_name='model',
        ),
        migrations.AddField(
            model_name='craft',
            name='numberOfSeats',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='craft',
            name='serialNumber',
            field=models.CharField(default='default', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manifest',
            name='flight',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Flight'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manifest',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Person'),
            preserve_default=False,
        ),
    ]
