# Generated by Django 3.0.5 on 2020-04-10 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200410_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='link_grubhub',
            new_name='grubhub_uername',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='link_linkedin',
            new_name='linkedin_username',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='link_twitter',
            new_name='twitter_username',
        ),
    ]
