# Generated by Django 3.0.5 on 2020-04-10 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200410_2343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='grubhub_uername',
            new_name='github_uername',
        ),
    ]
