# Generated by Django 3.0.5 on 2020-04-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20200413_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='first_name',
            field=models.CharField(default='Sandy', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(default='Shore', max_length=30),
            preserve_default=False,
        ),
    ]
