# Generated by Django 3.0.5 on 2020-04-13 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_auto_20200413_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='craft',
            old_name='numberOfSeats',
            new_name='seats',
        ),
        migrations.RenameField(
            model_name='craft',
            old_name='serialNumber',
            new_name='serial_number',
        ),
    ]
